<?php

namespace ADOB\SenofficeBundle\Repository;

/**
 * CarrondissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarrondissementRepository extends \Doctrine\ORM\EntityRepository
{
}
