<?php

namespace ADOB\SenofficeBundle\Repository;

/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommuneRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommune($commune)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT C FROM SenofficeBundle:Commune as C WHERE C.nomCommune LIKE '".$commune."%'");
        // $query->setParameter();
        $result = $query->getResult();

        return $result;
    }
}
