<?php

namespace ADOB\SenofficeBundle\Repository;

/**
 * TypedebienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypedebienRepository extends \Doctrine\ORM\EntityRepository
{
}
